# Generated by Django 4.0.1 on 2022-01-11 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=3000)),
                ('image', models.ImageField(upload_to='uploads')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 1, 11, 11, 7, 26, 926746))),
                ('detail', models.CharField(max_length=150)),
            ],
        ),
    ]
